accounts/urls.py
from django.urls import path
from .views import login

app_name = 'accounts'


urlpatterns = [
    path('',login,name= 'organization_login'),
    
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace='accounts')),
    path('organization/',include('organization.urls',namespace='organization')),
    path('marketing/',include('marketing.urls',namespace='marketing')),
    path('security/',include('security.urls',namespace='security')),
]

organization/urls.py
from django.urls import path
from .views import index,file_upload
app_name = 'organization'
urlpatterns = [
    path('', index, name = 'index'),
    path('upload/',file_upload,name= "upload_file"),
    

]

accounts/models.py
from django.db import models

# src/users/model.py
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser




class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


# src/users/model.py


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email




#creates a model to hold extra fields of registration
class ExtraDetails(models.Model):
    APPLICATION = 'AP'
    MARKETING = 'MT'
    SECURITY = 'ST'
    KAPS = 'PK'
    DEPARTMENT_CHOICES = [
        (APPLICATION, 'Application'),
        (MARKETING, 'Marketing'),
        (SECURITY, 'Security'),
        (KAPS, 'Kaps'),

    ]


    #organizations 
    RESIDENTIAL = 'RS'
    NONRESIDENTIAL = 'NR'
    RESIDENTIAL_NONRESIDENTIAL_CHOICES = [
        (RESIDENTIAL, 'Residential'),
        (NONRESIDENTIAL, 'Non Residential'),

    ]

    #governmental non governmenta
    GOVERNMENTAL = 'GR'
    NONGOVERNMENTAL = 'NG'
    GOVERNMENTAL_NONGOVERNMENTAL_CHOICES = [
        (GOVERNMENTAL, 'Governmental'),
        (NONGOVERNMENTAL, 'Non Governmental'),

    ]
    ORGANIZATION_CHOICES = [
    ('RESIDENTIAL_GOVERNMENTAL', (
            ('vinyl', 'Vinyl'),
            ('cd', 'CD'),
        )
    ),
    ('RESIDENTIAL_NON_GOVERNMENTAL', (
            ('vhs', 'VHS ape'),
            ('dvd', 'DVD'),
        )
    ),

    ('NON_RESIDENTIAL_NON_GOVERNMENTAL', (
            ('vhs', 'VHS Tape'),
            ('dvd', 'DVD'),
        )
    ),
    ('NON_RESIDENTIAL_GOVERNMENTAL', (
            ('vhs', 'VHS Tape'),
            ('dvd', 'DVD'),
        )
    ),

    
]
    user =  models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    first_name =  models.CharField(max_length=255)
    last_name =  models.CharField(max_length=255)
    id_number = models.IntegerField()
    tag_number = models.CharField(max_length=255)
    department =  models.CharField(max_length=2,choices=DEPARTMENT_CHOICES,default=APPLICATION)
    residential_non_residential_organization = models.CharField(max_length=2,choices=RESIDENTIAL_NONRESIDENTIAL_CHOICES,default=RESIDENTIAL)
    governmental_non_govermental = models.CharField(max_length=2,choices=GOVERNMENTAL_NONGOVERNMENTAL_CHOICES,default=GOVERNMENTAL)
    organization = models.CharField(max_length=255,choices=ORGANIZATION_CHOICES,default=APPLICATION)
    
    def __str__(self):
        return str(self.tag_number)
        
    
    

organization/models.py
from django.db import models
from accounts.models import ExtraDetails
# Create your models here.
from accounts.models import CustomUser
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from config.utils import unique_slug_generator
#this provides an organization 
class Applicants(models.Model):

    PENDING = "PD"
    APPROVED = "AP"
    REJECTED = "RJ"
    APPLICATION_CHOICES =  [
         (PENDING, 'pending'),
        (APPROVED, 'approved'),
        (REJECTED, 'rejected'),

    ]
    organization =  models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    applicants_name = models.CharField(max_length=255)
    applicants_id_number  =  models.IntegerField()
    applicants_tag_number =  models.CharField(max_length=255)
    applicants_phone_number =  models.CharField(max_length=255)
    applicants_email =  models.EmailField()
    #todo : the departments need to be a list which needs to be provided for so that we enter the lists as categories of department
    applicants_department = models.CharField(max_length=255)
    applicants_vehicle_type =  models.CharField(max_length=255)
    applicants_car_reg_number = models.CharField(max_length=255)
    applicants_log_book_number =  models.CharField(max_length=255)
    #this shows the current duration when the pass needs to be visible
    aplicants_duration =  models.CharField(max_length=255)
    aplicants_status =  models.CharField(max_length=2,choices=APPLICATION_CHOICES,default=PENDING)
    #check if the date when the application was send
    application_send_date =  models.DateTimeField(auto_now=True)
    #check to see the application status
    #this shows if the application is active or not or if it needs renewals
    application_active = models.BooleanField(default=True)
    #marketing approved 
    applicants_marketing_approved =  models.BooleanField(default=False)
    applicants_security_approved =  models.BooleanField(default=False)
    applicants_kaps_issue =  models.BooleanField(default=False)
    slug = models.SlugField(blank=True,unique=True)



    def get_absolute_url(self):
        return reverse("marketing:delete_applicants", kwargs={
            'slug': self.slug
        })
    def __str__(self):
        return self.applicants_email

def product_presave_reciver(sender, instance, *args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_presave_reciver,sender = Applicants)
    
    



    

accounts/views.py
from django.contrib.auth import authenticate, get_user_model, login
from django.shortcuts import render,redirect
from organization.models import Applicants
from .models import CustomUser,ExtraDetails

# Create your views here.

def login(request):
    if request.POST:
        email = request.POST.get('emailAddress')
        password =  request.POST.get('loginPassword')
        user = CustomUser(email = email, password = password)
        if user is not None:
            objectsss = Applicants.objects.all()
            get_email =  ExtraDetails.objects.all()
            for m in get_email:
                if str(m.user) ==  str(user):
                    if str(m.department)  == 'AP':
                        request.session["account_user"] =  str(user)
                        return redirect('organization:index')
                    elif str(m.department)  == 'MT':
                        request.session["account_user"] =  str(user)
                        return redirect('marketing:index')
                    elif str(m.department)  == 'ST':
                        request.session["account_user"] =  str(user)
                        return redirect('security:index')
            context = {
                "applicants" : objectsss
            }
            
    
                   

                
    return render(request,'organization/signin.html',{})

organization/views.py
from django.shortcuts import render,redirect
import pandas as pd
from .models import  Applicants
from accounts.models import CustomUser
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView,View,ListView
from django.shortcuts import get_object_or_404

# Create your views here.
def index(request):
    applicants  = Applicants.objects.all()
    context = {
        'application' : applicants
    }
    return render(request,'index.html',context)


def file_upload(request):
    if request.method ==  "POST":
        uploaded_files =  request.FILES["excel_file"]
        upload_name =  uploaded_files.name
        df = pd.read_excel (uploaded_files)
        accounts_name = request.session.get("account_user")
        user =  CustomUser.objects.get(email=accounts_name)
        applicants  = Applicants.objects.all()
        for index, row in df.iterrows():
            app = Applicants(
                organization = user,
                applicants_name=row["Applicant_Name"],
                applicants_id_number = row["Applicant_ID"],
                applicants_tag_number = row["Applicant_Tag_NO"],
                applicants_phone_number = row["Applicant_Phone_Number"],
                applicants_email = row["Applicant_Email"],
                applicants_department = row["Applicant_Department"],
                applicants_vehicle_type = row["Applicant_Vehicle_Type"],
                applicants_car_reg_number = row["Applicant_Car_Reg_NO"],
                applicants_log_book_number = row["Applicant_Log_Book_NO"],
                aplicants_duration = row["Applicant_Duration"]
                
            )
            app.save()
           
    context = {
        'application' : applicants
    }
    return render(request,'index.html',context)

accounts/templates/organization/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">
<link href="{% static 'images/logo.png' %}" rel="icon">
<title>Organization Login</title>
<meta name="description" content="Login and Register Form Html Template">
<meta name="author" content="harnishdesign.net">

<!-- Web Fonts
========================= -->
<link rel='stylesheet' href='../../css.css?family=Poppins:100,200,300,400,500,600,700,800,900' type='text/css'>

<!-- Stylesheet
========================= -->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'vendor/font-awesome/css/all.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
<!-- Colors Css -->
<link id="color-switcher" type="text/css" rel="stylesheet" href="css/color-purple.css">
</head>
<body>

<!-- Preloader -->
<div class="preloader preloader-dark">
  <div class="lds-ellipsis">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>
</div>
<!-- Preloader End -->

<div id="main-wrapper" class="oxyy-login-register">
  <div class="hero-wrap d-flex align-items-center h-100">
    <div class="hero-mask opacity-8 bg-dark"></div>
    <div class="hero-bg hero-bg-scroll" style="background-image:url('{% static 'images/login-bg-4.jpg' %}');"></div>
    <div class="hero-content w-100 h-100">
      <div class="container">
        <div class="row no-gutters min-vh-100">
          <div class="col-lg-11 col-xl-9 mx-auto">
            <div class="row no-gutters min-vh-100"> 
              <!-- Welcome Text
      ========================= -->
              <div class="col-md-6">
                <div class="hero-wrap d-flex align-items-center h-100">
                  <div class="hero-mask opacity-7 bg-primary"></div>
                  <div class="hero-bg hero-bg-scroll" style="background-image:url('{% static 'images/login-bg.jpg' %}');"></div>
                  <div class="hero-content mx-auto w-100 h-100 d-flex flex-column">
                    <div class="row no-gutters">
                      <div class="col-10 col-lg-9 mx-auto">
                        <div class="logo mt-5 mb-5 mb-md-0"> <a class="d-flex" href="index.html" title="Oxyy"><img src="{% static 'images/logo.png' %}" alt="Logo" width="280" height="250"></a> </div>
                      </div>
                    </div>
                    <div class="row no-gutters my-auto">
                      <div class="col-10 col-lg-9 mx-auto">
                        <h1 class="text-10 text-white font-weight-700 text-uppercase mb-4">WELCOME TO THE CAR STICKER APPLICATION DASHBOARD.</h1>
                        <p class="text-white font-weight-300 line-height-4 mb-5">Use The Loging Credentials Provided By The Marketing Department.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Welcome Text End --> 
              <!-- Login Form
      ========================= -->
              <div class="col-md-6 d-flex flex-column bg-light shadow-lg">
                <div class="container my-auto py-5">
                  <div class="row no-gutters">
                    <div class="col-11 col-lg-10 mx-auto">
                      <h3 class="text-6 font-weight-600">Log In</h3>
                      <form  class="form-border" method="POST" action = '{% url "accounts:organization_login" %}'>
                          {% csrf_token %}
                          <div class="form-group icon-group icon-group-right">
                              <input type="email" class="form-control border-dark" name="emailAddress" required="" placeholder="Email">
                              <span class="icon-inside"><i class="fas fa-envelope"></i></span>
                          </div>
                          <div class="form-group icon-group icon-group-right">
                              <input type="password" class="form-control border-dark" name="loginPassword" required="" placeholder="Password">
                              <span class="icon-inside"><i class="fas fa-lock"></i></span>
                          </div>
                          <div class="form-check custom-control custom-checkbox mt-4">
                              <input id="remember-me" name="remember" class="custom-control-input" type="checkbox">
                              <label class="custom-control-label rounded-0" for="remember-me">Remember Me</label>
                          </div>
                          <div class="form-group">
                              <button class="btn btn-primary rounded-0 my-4" type="submit">Log In</button>
                          </div>
                      </form>
                     
                    </div>
                  </div>
                </div>
                <div class="container pt-2 pb-3">
                  <div class="row">
                    <div class="col-11 col-lg-10 mx-auto">
                    </div>
                  </div>
                </div>
              </div>
              <!-- Login Form End --> 
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Video Modal
========================= -->
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content bg-transparent border-0">
      <button type="button" class="close text-white opacity-10 ml-auto mr-n3 font-weight-400" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-body p-0">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" id="video" allow="autoplay"></iframe>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Video Modal end --> 

<!-- Styles Switcher -->
<div id="styles-switcher" class="left">
  <h5>Color Switcher</h5>
  <hr>
  <ul class="mb-0">
    <li class="blue" data-toggle="tooltip" title="Blue" data-path="#"></li>
    <li class="indigo" data-toggle="tooltip" title="Indigo" data-path="{% static 'css/color-indigo.css' %}"></li>
    <li class="purple" data-toggle="tooltip" title="Purple" data-path="{% static 'css/color-purple.css' %}"></li>
    <li class="pink" data-toggle="tooltip" title="Pink" data-path="{% static 'css/color-pink.css' %}"></li>
    <li class="red" data-toggle="tooltip" title="Red" data-path="{% static 'css/color-red.css' %}"></li>
    <li class="orange" data-toggle="tooltip" title="Orange" data-path="{% static 'css/color-orange.css' %}"></li>
    <li class="yellow" data-toggle="tooltip" title="Yellow" data-path="{% static 'css/color-yellow.css' %}"></li>
    <li class="teal" data-toggle="tooltip" title="Teal" data-path="{% static 'css/color-teal.css' %}"></li>
    <li class="green" data-toggle="tooltip" title="Green" data-path="{% static 'css/color-green.css' %}"></li>
    <li class="cyan" data-toggle="tooltip" title="Cyan" data-path="{% static 'css/color-cyan.css' %}"></li>
    <li class="brown" data-toggle="tooltip" title="Brown" data-path="{% static 'css/color-brown.css' %}"></li>
  </ul>
  <button class="btn switcher-toggle"><i class="fas fa-cog"></i></button>
</div>
<!-- Styles Switcher End --> 

<!-- Script --> 
<script src=" {% static 'vendor/jquery/jquery.min.js' %}"></script> 
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> 
<!-- Style Switcher --> 
<script src="{% static 'js/switcher.min.js' %}"></script> 
<script src="{% static 'js/theme.js' %}"></script>
</body>
</html>